---
- name: enable lz4 compression on main pool
  become: true
  community.general.zfs:
    name: main
    state: present
    extra_zfs_properties:
      compression: lz4

- name: create datasets
  become: true
  community.general.zfs:
    name: main/{{ item }}
    state: present
    extra_zfs_properties:
      compression: lz4
  loop:
    - data
    - testing
    - jellyfin
    - stump

- name: ensure user 1000 owns the datasets dirs
  become: true
  file:
    path: /main/{{ item }}
    owner: 1000
    group: 1000
    mode: '0755'
  loop:
    - data
    - testing
    - jellyfin
    - stump

