---
services:
  heimdall:
    image: linuxserver/heimdall:2.7.4
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./config:/config
    ports:
      - 8080:80
    restart: unless-stopped
    labels:
      - 'wud.tag.include=^\d+.\d+.\d+$'
      - 'wud.tag.exclude=2021'
