---
- name: create install directory
  become: yes
  ansible.builtin.file:
    path: /opt/appflowy
    state: directory
    owner: riley
    group: riley

- name: copy environment file
  ansible.builtin.template:
    src: env.j2
    dest: /opt/appflowy/.env
    owner: riley
    group: riley

- name: Copy docker compose file
  ansible.builtin.copy:
    src: docker-compose.yml
    dest: /opt/appflowy/docker-compose.yml
    owner: riley
    group: riley

- name: Copy internal nginx conf file
  ansible.builtin.copy:
    src: nginx.conf
    dest: /opt/appflowy/nginx.conf
    owner: riley
    group: riley

- name: restart_gotrue
  ansible.builtin.shell:
    chdir: /opt/appflowy
    cmd: docker compose pull && docker compose down --remove-orphans && docker compose up -d && docker compose rm

