services:
  searxng:
    container_name: searxng
    image: docker.io/searxng/searxng:2025.5.5-0315988f5
    restart: unless-stopped
    user: 1000:1000
    ports:
      - "8005:8080"
    volumes:
      - ./searxng:/etc/searxng:rw
    environment:
      - SEARXNG_BASE_URL=https://${SEARXNG_HOSTNAME:-search.rileymathews.com}/
      - UWSGI_WORKERS=${SEARXNG_UWSGI_WORKERS:-4}
      - UWSGI_THREADS=${SEARXNG_UWSGI_THREADS:-4}
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID

