services:
  beszel:
    image: henrygd/beszel:latest
    container_name: beszel
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./data:/beszel_data
    ports:
      - 8090:8090
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
