services:
  homebridge:
    image: homebridge/homebridge:2025-09-15
    restart: always
    network_mode: host
    labels:
      - 'wud.tag.include=^\d+-\d+-\d+$'
    volumes:
      - ./data/homebridge:/homebridge
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"
