---
services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:2.6.3
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./config:/config
    ports:
      - 8080:80
    restart: unless-stopped

