---
- name: install nfs client packages
  become: true
  ansible.builtin.pacman:
    name:
      - nfs-utils
    state: present

- name: enable nfs-client target
  become: true
  ansible.builtin.systemd:
    name: nfs-client.target
    enabled: yes
    state: started

- name: create mount points
  become: true
  ansible.builtin.file:
    path: /mnt/{{ item }}
    state: directory
    owner: 1000
    group: 1000
    mode: '0755'
  with_items: "{{ nfs_mounts }}"

- name: mount nfs shares
  become: true
  ansible.posix.mount:
    src: nas:{{ item }}
    path: /mnt/{{ item }}
    fstype: nfs
    state: mounted
  with_items: "{{ nfs_mounts }}"

