---
- name: install nfs client packages
  become: true
  community.general.pacman:
    name:
      - nfs-utils
    state: present
  when: ansible_os_family == 'Archlinux'

- name: install nfs client packages
  become: true
  ansible.builtin.apt:
    name:
      - nfs-common
    state: present
  when: ansible_os_family == 'Debian'

- name: enable nfs-client target
  become: true
  ansible.builtin.systemd:
    name: nfs-client.target
    enabled: yes
    state: started

- name: create mount points
  become: true
  ansible.builtin.file:
    path: /mnt/{{ item }}
    state: directory
    owner: "{{ owning_user_id | default(1000) }}"
    group: "{{ owning_user_id | default(1000) }}"
    mode: '0755'
  with_items: "{{ nfs_mounts }}"

- name: add mounts to fstab
  become: true
  ansible.posix.mount:
    src: nas:{{ item }}
    path: /mnt/{{ item }}
    fstype: nfs
    opts: "defaults,nofail,x-systemd.after=tailscaled.service"
    state: present
  with_items: "{{ nfs_mounts }}"

- name: mount nfs shares
  become: true
  ansible.posix.mount:
    src: nas:{{ item }}
    path: /mnt/{{ item }}
    fstype: nfs
    state: mounted
  with_items: "{{ nfs_mounts }}"

