# vim:ft=yaml.ansible
---
- hosts: holosuite
  vars:
    available_sites:
      - name: appflowy
        listen_host: "appflowy.rileymathews.com"
        backend_host: "http://127.0.0.1:8000"
    dns_records:
      - "appflowy"
  roles:
    - appflowy
    - certbot
    - proxy
    - dns_records

