---
- hosts: all
  become: yes
  roles:
    - tailscale

- hosts: all
  become: yes
  roles:
    - setup_git

- hosts: docker
  become: yes
  roles:
    - install_docker

- hosts: reverse_proxy
  become: yes
  roles:
    - certbot
