---
- name: Copy SSH keys to target user on remote machines
  hosts: all
  become: yes
  tasks:
    - name: Ensure .ssh directory exists
      file:
        path: "/home/{{ target_user }}/.ssh"
        state: directory
        owner: "{{ target_user }}"
        group: "{{ target_user }}"
        mode: '0700'

    - name: Copy the private SSH key to the remote machine
      copy:
        src: "{{ ssh_private_key_path }}"
        dest: "/home/{{ target_user }}/.ssh/id_ed25519"
        owner: "{{ target_user }}"
        group: "{{ target_user }}"
        mode: '0600'

    - name: Copy the public SSH key to the remote machine
      copy:
        src: "{{ ssh_public_key_path }}"
        dest: "/home/{{ target_user }}/.ssh/id_ed25519.pub"
        owner: "{{ target_user }}"
        group: "{{ target_user }}"
        mode: '0644'

  vars:
    target_user: "riley"
    ssh_private_key_path: "/home/riley/.ssh/id_ed25519"
    ssh_public_key_path: "/home/riley/.ssh/id_ed25519.pub"

