---
- hosts: gateway
  become: yes
  vars:
    available_sites:
      - name: whoami
        listen_host: "whoami-gateway.rileymathews.com"
        backend_host: "http://enterprise:8006"
      - name: rpgweave-staging
        listen_host: "staging.rpgweave.com"
        backend_host: "http://rpgweave-staging:80"
      - name: rpgweave
        listen_host: "rpgweave.com"
        backend_host: "http://rpgweave:80"
      - name: vaultwarden
        listen_host: "vaultwarden.rileymathews.com"
        backend_host: "http://vaultwarden:8000"
    dns_records:
      - "whoami-gateway"
      - "vaultwarden"
    override_ipv4: "45.33.103.133"
  roles:
    - certbot
    - proxy
    - dns_records
