---

- hosts: all
  become: yes
  roles:
    - geerlingguy.docker

  tasks:
    - name: Add user 'riley' to the docker group
      user:
        name: riley
        groups: docker
        append: yes
