---
- hosts: tailscale
  become: yes
  roles:
    - tailscale

- hosts: docker
  become: yes
  roles:
    - install_docker
    - diun

- hosts: awscli
  become: true
  roles:
    - awscli2

- hosts: public_tcp_proxy
  become: yes
  roles:
    - setup-ha-proxy

- hosts: certbot
  become: yes
  roles:
    - certbot

- hosts: hoshi.local
  roles:
    - pihole

- hosts: proxy
  become: yes
  roles:
    - proxy

- hosts: homeassistant.local
  roles:
    - homeassistant

- hosts: k8s
  roles:
    - k8s-common

- hosts: k8s_ctrlr
  roles:
    - k8s_ctrlr

- hosts: k8s_worker
  roles:
    - k8s_worker

- hosts: bynar.local
  roles:
    - redis

- hosts: worf.local
  roles:
   - vaultwarden

- hosts: uhura.local
  roles:
   - rabbitmq

- hosts: memory-alpha.local
  roles:
    - pg_install
    - pg_backup
    - pg_setup

- hosts: restic
  roles:
    - restic

- hosts: barclay.local
  roles:
    - gitea

- hosts: enterprise.local
  roles:
    - heimdall
    - gatus
    - open_web_ui
    - vikunja
    - ntfy
    - searxng
    - whoami

- hosts: neelix.local
  roles:
    - mealie

- hosts: data.local
  roles:
    - nvidia_docker
    - ollama

- hosts: laforge.local
  roles:
    - grafana

- hosts: obrien.local
  roles:
    - gitea-runner

- hosts: zfs-testing.local
  roles:
    - role: zfs
      vars:
        zfs_devices:
          - /dev/sdb
          - /dev/sdc
          - /dev/sdd
          - /dev/sde

