---
- hosts: all
  become: yes
  roles:
    - tailscale

- hosts: all
  become: yes
  roles:
    - copy_ssh_identity


- hosts: all
  become: yes
  roles:
    - setup_git

- hosts: docker
  become: yes
  roles:
    - install_docker
