---
- hosts: tailscale
  become: yes
  roles:
    - tailscale

- hosts: docker
  become: yes
  roles:
    - install_docker

- hosts: public_tcp_proxy
  become: yes
  roles:
    - setup-ha-proxy

- hosts: proxy
  become: yes
  roles:
    - proxy

- hosts: rpgweave
  become: yes
  roles:
    - rpgweave

- hosts: homeassistant.local
  roles:
    - homeassistant

- hosts: searxng.local
  roles:
    - searxng

- hosts: ntfy.local
  roles:
    - ntfy

- hosts: k8s
  roles:
    - k8s

- hosts: redis
  roles:
    - redis

- hosts: vaultwarden.local
  roles:
   - vaultwarden

- hosts: rabbitmq.local
  roles:
   - rabbitmq
