---
- hosts: all
  become: yes
  roles:
    - tailscale

- hosts: docker
  become: yes
  roles:
    - install_docker

- hosts: reverse_proxy
  become: yes
  roles:
    - certbot

- hosts: public_tcp_proxy
  become: yes
  roles:
    - setup-ha-proxy
