---
- hosts: tailscale
  become: yes
  roles:
    - tailscale

- hosts: docker
  become: yes
  roles:
    - install_docker

- hosts: awscli
  become: true
  roles:
    - awscli2

- hosts: public_tcp_proxy
  become: yes
  roles:
    - setup-ha-proxy

- hosts: certbot
  become: yes
  roles:
    - certbot

- hosts: pi-hole.local
  roles:
    - pihole

- hosts: proxy
  become: yes
  roles:
    - proxy

- hosts: rpgweave
  become: yes
  roles:
    - rpgweave

- hosts: homeassistant.local
  roles:
    - homeassistant

- hosts: searxng.local
  roles:
    - searxng

- hosts: ntfy.local
  roles:
    - ntfy

- hosts: k8s
  roles:
    - k8s-common

- hosts: k8s_ctrlr
  roles:
    - k8s_ctrlr

- hosts: k8s_worker
  roles:
    - k8s_worker

- hosts: redis
  roles:
    - redis

- hosts: vaultwarden.local
  roles:
   - vaultwarden

- hosts: rabbitmq.local
  roles:
   - rabbitmq

- hosts: db1.local
  roles:
    - pg_install
    - pg_backup
    - pg_setup

- hosts: restic
  roles:
    - restic

- hosts: vikunja.local
  roles:
    - vikunja
