---
- hosts: all
  roles:
    - setup-shell

# - hosts: all
#   become: yes
#   roles:
#     - prometheus.prometheus.node_exporter

- hosts: tailscale
  become: yes
  roles:
    - tailscale

- hosts: engineering.local
  roles:
    - prometheus

- hosts: docker
  become: yes
  roles:
    - install_docker

- hosts: awscli
  become: true
  roles:
    - awscli2

- hosts: public_tcp_proxy
  become: yes
  roles:
    - setup-ha-proxy

- hosts: certbot
  become: yes
  roles:
    - certbot

- hosts: hoshi.local
  roles:
    - pihole

- hosts: proxy
  become: yes
  roles:
    - proxy

- hosts: homeassistant.local
  roles:
    - homeassistant

- hosts: k8s
  roles:
    - k8s-common

- hosts: k8s_ctrlr
  roles:
    - k8s_ctrlr

- hosts: k8s_worker
  roles:
    - k8s_worker

- hosts: bynar.local
  roles:
    - redis

- hosts: worf.local
  roles:
   - vaultwarden

- hosts: uhura.local
  roles:
   - rabbitmq

- hosts: memory-alpha.local
  roles:
    - pg_install
    - pg_backup
    - pg_setup

- hosts: restic
  roles:
    - restic

- hosts: barclay.local
  roles:
    - gitea

- hosts: enterprise.local
  roles:
    - heimdall
    - gatus
    - open_web_ui
    - vikunja
    - ntfy
    - searxng
    - whoami
    - lubelogger
    - paperless

- hosts: holodeck.local
  roles:
    - whoami
    - nextcloud

- hosts: neelix.local
  roles:
    - mealie

- hosts: laforge.local
  roles:
    - role: grafana.grafana.grafana
      vars:
        grafana_ini:
          security:
            admin_user: admin
            admin_password: "{{ grafana_admin_password }}"

- hosts: obrien.local
  roles:
    - gitea-runner

- hosts: section31.local
  roles:
    - synapse

- hosts: all
  roles:
    - dns_records

- hosts: nas.local
  roles:
    - zfs
    - nas-nfs
