---
- hosts: all
  roles:
    - setup-shell

- hosts: docker
  become: yes
  roles:
    - install_docker

- hosts: awscli
  become: true
  roles:
    - awscli2

- hosts: public_tcp_proxy
  become: yes
  roles:
    - setup-ha-proxy

- hosts: hoshi.local
  roles:
    - pihole

- hosts: homeassistant.local
  roles:
    - homeassistant

- hosts: k8s
  roles:
    - k8s-common

- hosts: k8s_ctrlr
  roles:
    - k8s_ctrlr

- hosts: k8s_worker
  roles:
    - k8s_worker

- hosts: bynar.local
  roles:
    - redis

- hosts: worf.local
  roles:
   - vaultwarden

- hosts: rabbitmq
  roles:
   - rabbitmq

- hosts: restic
  roles:
    - restic

- hosts: enterprise.local
  roles:
    - heimdall
    - gatus
    - open_web_ui
    - vikunja
    - ntfy
    - searxng
    - whoami
    - lubelogger
    - paperless

- hosts: obrien.local
  roles:
    - gitea-runner

- hosts: section31.local
  roles:
    - synapse

- hosts: nas.local
  roles:
    - zfs
    - nas-nfs
