---
- name: restart_homeassistant
  ansible.builtin.shell:
    chdir: /opt/homeassistant
    cmd: docker compose pull && docker compose down --remove-orphans && docker compose up -d && docker compose rm
