services:
  immich-machine-learning:
    container_name: immich_machine_learning
    labels:
      - wud.tag.include=^v\d+\.\d+\.\d+$$
    image: ghcr.io/immich-app/immich-machine-learning:v1.138.1
    volumes:
      - model-cache:/cache
    restart: always
    ports:
      - 3003:3003
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu

volumes:
  model-cache:
