services:
  vikunja:
    image: registry:3
    ports:
      - 5000:5000
    volumes:
      - /mnt/main/docker_images:/var/lib/registry
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/registry
    restart: unless-stopped
