services:
  radicale:
    image: ghcr.io/kozea/radicale:3.5.4
    user: root
    ports:
      - "5232:5232"
    volumes:
      - /mnt/main/radicale/config:/etc/radicale:ro
      - /mnt/main/radicale/data:/var/lib/radicale
    restart: unless-stopped
