---
- name: create install directory
  become: yes
  ansible.builtin.file:
    path: /opt/wud
    state: directory
    owner: riley
    group: riley

- name: Copy docker compose file
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: /opt/wud/docker-compose.yml
    owner: riley
    group: riley
  notify: restart_wud

