---
- name: create install directory
  become: yes
  ansible.builtin.file:
    path: /opt/open-web-ui
    state: directory
    owner: riley
    group: riley

- name: Copy docker compose file
  ansible.builtin.copy:
    src: docker-compose.yml
    dest: /opt/open-web-ui/docker-compose.yml
    owner: riley
    group: riley
  notify: restart_open_web_ui


