services:
  whatsupdocker:
    image: getwud/wud
    container_name: wud
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 3000:3000
    environment:
        -  WUD_WATCHER_LOCAL_SOCKET=/var/run/docker.sock
        -  WUD_WATCHER_HOLODECK_HOST=holodeck
