---
- name: Install on debian systems
  include_tasks: install_debian.yml
  when: ansible_facts['os_family'] == 'Debian'

- name: Install on arch systems
  include_tasks: install_arch.yml
  when: ansible_facts['os_family'] == 'Archlinux'

- name: Ensure systemd override directory for nginx exists
  become: true
  ansible.builtin.file:
    path: /etc/systemd/system/nginx.service.d
    state: directory
    mode: '0755'

- name: Create systemd override for nginx to wait for tailscale
  become: true
  ansible.builtin.copy:
    dest: /etc/systemd/system/nginx.service.d/override.conf
    content: |
      [Unit]
      After=tailscaled.service
      Wants=tailscaled.service
    mode: '0644'
    owner: root
    group: root
  notify:
    - restart_systemd
    - restart_nginx

- name: Copy nginx conf file
  become: true
  ansible.builtin.copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: '0644'
  notify: reload_nginx

- name: Create sites-available directory
  become: true
  ansible.builtin.file:
    path: /etc/nginx/sites-available
    state: directory

- name: Create site available files
  become: true
  ansible.builtin.template:
    src: site.conf.j2
    dest: "/etc/nginx/sites-available/{{ item.name }}.conf"
    owner: root
    group: root
    mode: '0644'
  loop: "{{ available_sites }}"
  notify: reload_nginx
  vars:
    listen_host: "{{ item.listen_host }}"
    backend_host: "{{ item.backend_host }}"

- name: Start nginx
  become: true
  ansible.builtin.systemd:
    name: nginx
    state: started
    enabled: true

