services:
  rpgweave:
    image: registry.gitlab.com/rpgweave/rpg_weave:${IMAGE_TAG-latest}
    env_file:
      - env.secret
    restart: unless-stopped
    ports:
      - 8000:8000

  celery:
    image: registry.gitlab.com/rpgweave/rpg_weave:${IMAGE_TAG-latest}
    env_file:
      - env.secret
    command: "./bin/celery"
    restart: unless-stopped

