---
- name: install git
  become: true
  pacman:
    name: git
    state: present
    update_cache: true

- name: install forgejo
  become: true
  pacman:
    name: forgejo
    state: present
    update_cache: true

- name: create custom config dir
  become: true
  become_user: git
  ansible.builtin.file:
    name: /mnt/main/forgejo/custom/conf
    state: directory
    owner: git
    group: git
    recurse: true

- name: copy custom config file
  become: true
  become_user: git
  ansible.builtin.template:
    src: app.ini.j2
    dest: /mnt/main/forgejo/custom/conf/app.ini
    owner: git
    group: git
  notify: restart_forgejo

- name: Ensure Forgejo systemd override directory exists
  become: true
  ansible.builtin.file:
    path: /etc/systemd/system/forgejo.service.d
    state: directory
    mode: '0755'

- name: Copy Forgejo systemd override file
  become: true
  ansible.builtin.copy:
    src: override.conf
    dest: /etc/systemd/system/forgejo.service.d/override.conf
    owner: root
    group: root
    mode: '0644'
  notify: 
    - reload_systemd
    - restart_forgejo

- name: start forgejo
  become: true
  ansible.builtin.service:
    name: forgejo
    state: started
    enabled: true
