---
- name: Ensure UFW is installed
  become: true
  ansible.builtin.apt:
    name: ufw
    state: present
    update_cache: true

- name: Allow SSH (port 22)
  become: true
  community.general.ufw:
    rule: allow
    port: '22'
    proto: tcp

- name: Allow HTTP (port 80)
  become: true
  community.general.ufw:
    rule: allow
    port: '80'
    proto: tcp

- name: Allow HTTPS (port 443)
  become: true
  community.general.ufw:
    rule: allow
    port: '443'
    proto: tcp

- name: Set default policies (deny incoming, allow outgoing)
  become: true
  community.general.ufw:
    policy: deny
    direction: incoming

- name: Enable UFW and ensure it's active on boot
  become: true
  community.general.ufw:
    state: enabled
