---
- name: download dependencies
  become: true
  ansible.builtin.apt:
    name: unzip
    state: present
    update_cache: true

# https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html
- name: Download awscliv2 installer.
  unarchive:
    src: "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"
    dest: "/tmp"
    remote_src: true
    creates: '/tmp/aws'
    mode: 0755

- name: Run the installer.
  command:
  args:
    cmd: "/tmp/aws/install"
    creates: /usr/local/bin/aws
  become: true
  register: aws_install

- name: "Show installer output."
  debug:
    var: aws_install
    verbosity: 2
