services:
  vikunja:
    image: vikunja/vikunja:latest
    env_file:
      - .env
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    ports:
      - 8003:3456
    volumes:
      - /mnt/main/vikunja/files:/app/vikunja/files
    restart: unless-stopped
