---
- name: Update APT package cache
  become: true
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600 # Cache is valid for 1 hour

- name: Upgrade all packages
  become: true
  ansible.builtin.apt:
    upgrade: dist
  register: apt_upgrade_result # Register the result of the upgrade task

- name: Autoremove unnecessary packages
  become: true
  ansible.builtin.apt:
    autoremove: yes

- name: Clean up the APT cache
  become: true
  ansible.builtin.apt:
    autoclean: yes

- name: Check if reboot is required
  become: true
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: reboot_required_file # Register the result of the stat check

- name: Reboot the server if required
  become: true
  ansible.builtin.reboot:
  when: reboot_required_file.stat.exists is defined and reboot_required_file.stat.exists # Conditional reboot

