apiVersion: v1
kind: Service
metadata:
  name: rpgweave
spec:
  ports:
    - name: http
      port: 80
      targetPort: rpgw-http
  selector:
    app: rpgweave
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-rpgweave
spec:
  ingressClassName: nginx
  rules:
    - host: rpgweave.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rpgweave
                port:
                  number: 80
