apiVersion: apps/v1
kind: Deployment
metadata:
  name: rpgweave
  labels:
    app: rpgweave
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rpgweave
  template:
    metadata:
      labels:
        app: rpgweave
    spec:
      containers:
        - name: rpgweave
          image: gitea.rileymathews.com/riley/rpg_weave:latest
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: config.settings.prod
            - name: ENCRYPTION_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rpgweave-encryption-password
                  key: ENCRYPTION_PASSWORD
          ports:
            - containerPort: 8000
              name: "rpgw-http"
          readinessProbe:
            httpGet:
              path: /
              port: 8000
              httpHeaders:
                - name: Host
                  value: rpgweave.com
            initialDelaySeconds: 10
            periodSeconds: 5
      imagePullSecrets:
        - name: gitea-registry
