---
- name: install dependencies
  become: true
  ansible.builtin.apt:
    name:
      - curl
      - gnupg2
      - apt-transport-https

    state: present
    update_cache: true

- name: add gpg keys
  become: true
  ansible.builtin.apt_key:
    url: "{{ item }}"
    state: present
  loop:
    - https://keys.openpgp.org/vks/v1/by-fingerprint/0A9AF2115F4687BD29803A206B73A36E6026DFCA
    - https://github.com/rabbitmq/signing-keys/releases/download/3.0/cloudsmith.rabbitmq-erlang.E495BB49CC4BBE5B.key
    - https://github.com/rabbitmq/signing-keys/releases/download/3.0/cloudsmith.rabbitmq-server.9F4587F226208342.key

- name: add repositories
  become: true
  ansible.builtin.apt_repository:
    repo: "{{ item }}"
    state: present
  loop:
    - "deb https://ppa1.rabbitmq.com/rabbitmq/rabbitmq-erlang/deb/debian bookworm main"
    - "deb https://ppa2.rabbitmq.com/rabbitmq/rabbitmq-erlang/deb/debian bookworm main"
    - "deb https://ppa1.rabbitmq.com/rabbitmq/rabbitmq-server/deb/debian bookworm main"
    - "deb https://ppa2.rabbitmq.com/rabbitmq/rabbitmq-server/deb/debian bookworm main"

- name: add packages
  become: true
  ansible.builtin.apt:
    name:
      - erlang-base
      - erlang-asn1
      - erlang-crypto
      - erlang-eldap
      - erlang-ftp
      - erlang-inets
      - erlang-mnesia
      - erlang-os-mon
      - erlang-parsetools
      - erlang-public-key
      - erlang-runtime-tools
      - erlang-snmp
      - erlang-ssl
      - erlang-syntax-tools
      - erlang-tftp
      - erlang-tools
      - erlang-xmerl
      - rabbitmq-server
    update_cache: true
    state: present

- name: add vhosts
  become: true
  community.rabbitmq.rabbitmq_vhost:
    name: "{{ item }}"
    state: present
  loop:
    - rpgweave-staging
    - rpgweave
    - radicale

- name: add users
  become: true
  community.rabbitmq.rabbitmq_user:
    user: "{{ item.username }}"
    password: "{{ item.password }}"
    permissions:
      - vhost: "{{ item.vhost }}"
        configure_priv: .*
        read_priv: .*
        write_priv: .*
    state: present
  loop:
    - username: rpgweave-staging
      password: "{{ rpgweave_staging_rabbitmq_password }}"
      vhost: rpgweave-staging
    - username: rpgweave
      password: "{{ rpgweave_rabbitmq_password }}"
      vhost: rpgweave
    - username: radicale
      password: "{{ radicale_rabbitmq_password }}"
      vhost: radicale
