---
- name: create directories
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: 1000
    group: 1000
    mode: '0755'
  loop:
    - /opt/pinchflat
    - /opt/pinchflat/config

- name: copy docker-compose file
  become: true
  ansible.builtin.copy:
    src: docker-compose.yml
    dest: /opt/pinchflat/docker-compose.yml
    owner: 1000
    group: 1000
  notify: restart_pinchflat
