---
- name: reload_systemd
  become: true
  ansible.builtin.systemd:
    daemon_reload: true

- name: restart_gitea
  become: true
  ansible.builtin.service:
    name: gitea
    state: restarted
    enabled: true
