services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    # user: 1000:1000
    ports:
      - 8096:8096
    volumes:
      - /opt/jellyfin/config:/config
      - /opt/jellyfin/cache:/cache
      - /mnt/main/jellyfin:/media:ro
    restart: 'unless-stopped'
    # Optional - alternative address used for autodiscovery
    environment:
      - JELLYFIN_PublishedServerUrl=https://jellyfin.rileymathews.com

