---
- name: Ensure NFS utilities are installed.
  become: true
  ansible.builtin.apt:
    name:
      - nfs-common
      - nfs-kernel-server
    state: present
    update_cache: yes

- name: copy /etc/exports
  become: true
  copy:
    src: exports
    dest: /etc/exports
    owner: root
    group: root
    mode: '0644'
  notify: reload_nfs

- name: enable nfs-kernel-server
  become: true
  service:
    name: nfs-kernel-server
    enabled: yes
    state: started
