# vim:ft=yaml.ansible
---
- name: create install directory
  become: yes
  ansible.builtin.file:
    path: /opt/homebridge
    state: directory
    owner: riley
    group: riley

- name: create data directories
  ansible.builtin.file:
    name: "{{ item }}"
    state: directory
    owner: riley
    group: riley
  loop:
    - /opt/homebridge/data

- name: Copy docker compose file
  ansible.builtin.copy:
    src: docker-compose.yml
    dest: /opt/homebridge/docker-compose.yml
    owner: riley
    group: riley
  notify: restart_homebridge

- name: Restart homebridge
  ansible.builtin.shell:
    chdir: /opt/homebridge
    cmd: docker compose pull && docker compose down --remove-orphans && docker compose up -d && docker compose rm
