---
- name: create dirs
  become: true
  file:
    path: "{{ item }}"
    state: directory
    owner: 1000
    group: 1000
    mode: 0755
  loop:
    - /opt/beszel-agent

- name: create docker-compose.yml
  become: true
  copy:
    src: docker-compose.yml
    dest: /opt/beszel-agent/docker-compose.yml
    owner: 1000
    group: 1000

- name: Restart to update
  ansible.builtin.shell:
    chdir: /opt/beszel-agent
    cmd: docker compose pull && docker compose down --remove-orphans && docker compose up -d && docker compose rm

