# vim:ft=yaml.ansible
---
- name: Install on debian systems
  ansible.builtin.include_tasks: install_debian.yml
  when: ansible_facts['os_family'] == 'Debian'

- name: Install on arch systems
  ansible.builtin.include_tasks: install_arch.yml
  when: ansible_facts['os_family'] == 'Archlinux'

- name: Set zsh as default shell for riley
  become: true
  ansible.builtin.user:
    name: riley
    shell: /bin/zsh

- name: Clone dotfiles repo
  ansible.builtin.git:
    repo: https://github.com/rileymathews/dotfiles
    dest: /home/riley/dotfiles

- name: Stow dotfiles
  ansible.builtin.shell:
    chdir: /home/riley/dotfiles
    cmd: "stow ."

- name: Copy term info file
  ansible.builtin.copy:
    src: terminfo.txt
    dest: /home/riley/terminfo.txt
    owner: 1000
    group: 1000
    mode: '0644'

- name: Compile term info
  ansible.builtin.shell:
    chdir: /home/riley
    cmd: "tic -x terminfo.txt"
