services:
  web:
    image: ghcr.io/karakeep-app/karakeep:0.26.0
    restart: unless-stopped
    user: "1000"
    volumes:
      - ./data:/data
    ports:
      - 3000:3000
    env_file:
      - .env
    environment:
      MEILI_ADDR: http://meilisearch:7700
      BROWSER_WEB_URL: http://chrome:9222
      DATA_DIR: /data # DON'T CHANGE THIS
  chrome:
    image: gcr.io/zenika-hub/alpine-chrome:124
    restart: unless-stopped
    labels:
      - 'wud.tag.includ=^\d+$$'
      - 'wud.tag.exclude=with'
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars
  meilisearch:
    image: getmeili/meilisearch:v1.15.2
    restart: unless-stopped
    labels:
      - 'wud.tag.include=^v\d+.\d+.\d+$'
    env_file:
      - .env
    environment:
      MEILI_NO_ANALYTICS: "true"
    volumes:
      - meilisearch:/meili_data

volumes:
  meilisearch:
