---
- name: install git
  become: true
  pacman:
    name: git
    state: present
    update_cache: true

- name: create git user
  become: true
  ansible.builtin.user:
    name: "git"
    system: true
    password: "!"
    state: "present"
    shell: "/bin/bash"
    create_home: true

- name: install gitea
  become: true
  pacman:
    name: gitea
    state: present
    update_cache: true

- name: create custom config dir
  become: true
  ansible.builtin.file:
    name: /var/lib/gitea/custom/conf
    state: directory
    owner: gitea
    group: gitea

- name: copy custom config file
  become: true
  ansible.builtin.template:
    src: app.ini.j2
    dest: /var/lib/gitea/custom/conf/app.ini
    owner: gitea
    group: gitea
  notify: restart_gitea

- name: start gitea
  become: true
  ansible.builtin.service:
    name: gitea
    state: started
    enabled: true
