storage:
  type: postgres
  path: "postgres://gatus:${POSTGRES_PASSWORD}@db1.tailscale.rileymathews.com:5432/gatus"


endpoint-defaults: &defaults
  group: Services
  interval: 30s
  client:
    timeout: 10s
  conditions:
    - "[STATUS] == 200"
    - "[CERTIFICATE_EXPIRATION] > 72h"
  alerts:
    - type: ntfy

alerting:
  ntfy:
    topic: "home-server-alerts"
    priority: 2
    url: "https://ntfy.rileymathews.com"
    default-alert:
      failure-threshold: 3
      send-on-resolved: true


endpoints:
  - name: rpgweave
    <<: *defaults
    url: "https://rpgweave.com/health_check"

  - name: vaultwarden
    <<: *defaults
    url: "https://vaultwarden.rileymathews.com"

  - name: homeassistant
    <<: *defaults
    url: "https://home.rileymathews.com"

  - name: mealie
    <<: *defaults
    url: "https://mealie.rileymathews.com"

  - name: forgejo
    <<: *defaults
    url: "https://forgejo.rileymathews.com"

  - name: karakeep
    <<: *defaults
    url: "https://karakeep.rileymathews.com"

  - name: immich
    <<: *defaults
    url: "https://immich.rileymathews.com"

  - name: miniflux
    <<: *defaults
    url: "https://miniflux.rileymathews.com"

  - name: vikunja
    <<: *defaults
    url: "https://vikunja.rileymathews.com"

  - name: searxng
    <<: *defaults
    url: "https://search.rileymathews.com"

  - name: radicale
    <<: *defaults
    url: "https://radicale.rileymathews.com"

  - name: nextcloud
    <<: *defaults
    url: "https://nextcloud.rileymathews.com"

  - name: audiobookshelf
    <<: *defaults
    url: "https://audiobookshelf.rileymathews.com"

  - name: WUD
    <<: *defaults
    url: "https://wud.rileymathews.com"
