services:
  gatus:
    image: twinproduction/gatus:latest
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    ports:
      - "8081:8080"
    env_file:
      - .env
    volumes:
      - ./config:/config

