services:
  homebridge:
    image: homebridge/homebridge:2025-05-16
    restart: always
    network_mode: host
    volumes:
      - ./data/homebridge:/homebridge
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"
