# vim:ft=yaml.ansible
---
- name: Nfs mounts
  include_role:
    name: mount-nfs
  vars:
    nfs_mounts:
      - main/mealie

- name: create install directory
  become: yes
  ansible.builtin.file:
    path: /opt/mealie
    state: directory
    owner: riley
    group: riley

- name: create data directories
  ansible.builtin.file:
    name: "{{ item }}"
    state: directory
    owner: riley
    group: riley
  loop:
    - /mnt/main/mealie/app/data

- name: Copy docker compose file
  ansible.builtin.copy:
    src: docker-compose.yml
    dest: /opt/mealie/docker-compose.yml
    owner: riley
    group: riley
  notify: restart_mealie

- name: Copy env template file
  ansible.builtin.template:
    src: .env.j2
    dest: /opt/mealie/.env
    owner: riley
    group: riley
  notify: restart_mealie

- name: restart_mealie
  ansible.builtin.shell:
    chdir: /opt/mealie
    cmd: docker compose pull && docker compose down --remove-orphans && docker compose up -d && docker compose rm
