---
- name: nfs mounts
  include_role:
    name: mount-nfs
  vars:
    nfs_mounts:
      - main/vaultwarden

- name: create install directory
  become: yes
  ansible.builtin.file:
    path: /opt/vaultwarden
    state: directory
    owner: riley
    group: riley

- name: create data directories
  ansible.builtin.file:
    name: "{{ item }}"
    state: directory
    owner: riley
    group: riley
  loop:
    - /mnt/main/vaultwarden/data

- name: Copy docker compose file
  ansible.builtin.copy:
    src: docker-compose.yml
    dest: /opt/vaultwarden/docker-compose.yml
    owner: riley
    group: riley

- name: Copy env file
  ansible.builtin.template:
    src: .env.j2
    dest: /opt/vaultwarden/.env
    owner: riley
    group: riley

- name: restart_vaultwarden
  ansible.builtin.shell:
    chdir: /opt/vaultwarden
    cmd: docker compose pull && docker compose down --remove-orphans && docker compose up -d && docker compose rm
