---
- name: create install directory
  become: yes
  ansible.builtin.file:
    path: /opt/vaultwarden
    state: directory
    owner: riley
    group: riley

- name: Copy docker compose file
  ansible.builtin.copy:
    src: docker-compose.yml
    dest: /opt/vaultwarden/docker-compose.yml
    owner: riley
    group: riley
  notify: restart_vaultwarden

