apiVersion: v1
kind: Pod
metadata:
  name: whoami-example
  labels:
    app: whoami
spec:
  containers:
    - name: whoami
      image: containous/whoami
      ports:
        - containerPort: 80
          name: "whoami-http"
