apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami-example
  labels:
    app: whoami
spec:
  replicas: 2
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
        - name: whoami
          image: containous/whoami
          ports:
            - containerPort: 80
              name: "whoami-http"
---
apiVersion: v1
kind: Service
metadata:
  name: whoami-example
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: whoami-http
  selector:
    app: whoami
