---
available_sites:
  - name: heimdall
    listen_host: start.rileymathews.com
    backend_host: "http://127.0.0.1:8080"

  - name: gatus
    listen_host: gatus.rileymathews.com
    backend_host: "http://127.0.0.1:8081"

  - name: open-web-ui
    listen_host: chat.rileymathews.com
    backend_host: "http://127.0.0.1:8082"

  - name: vikunja
    listen_host: "vikunja.rileymathews.com"
    backend_host: "http://127.0.0.1:8003"

accept_tcp_proxy: false
restic_backup_dirs:
  - /opt/vikunja/files
  - /opt/vikunja/db
