---
- name: create install directory
  become: yes
  ansible.builtin.file:
    path: /opt/ntfy
    state: directory
    owner: riley
    group: riley

- name: copy server file
  ansible.builtin.copy:
    src: server.yml
    dest: /opt/ntfy/server.yml
    owner: riley
    group: riley

- name: Copy docker compose file
  ansible.builtin.copy:
    src: docker-compose.yml
    dest: /opt/ntfy/docker-compose.yml
    owner: riley
    group: riley
  notify: restart_ntfy

