services:
  stump:
    image: aaronleopold/stump:latest
    container_name: stump
    restart: unless-stopped
    # Replace my paths (prior to the colons) with your own
    volumes:
      - /opt/stump/config:/config
      - /mnt/main/stump/data:/data
    ports:
      - 10801:10801
    environment:
      - PUID=1000
      - PGID=1000

