---
- name: create dirs
  become: true
  file:
    path: "{{ item }}"
    state: directory
    owner: 1000
    group: 1000
    mode: 0755
  loop:
    - /opt/beszel-hub
    - /opt/beszel-hub/data

- name: create docker-compose.yml
  become: true
  copy:
    src: docker-compose.yml
    dest: /opt/beszel-hub/docker-compose.yml
    owner: 1000
    group: 1000
  notify: restart_beszel
