---
- name: reload_nginx
  become: true
  ansible.builtin.service:
    name: nginx
    state: reloaded

- name: restart_systemd
  become: true
  ansible.builtin.systemd:
    daemon_reload: yes

- name: restart_nginx
  become: true
  ansible.builtin.systemd:
    name: nginx
    state: restarted

