---
available_sites:
  - name: gitea
    listen_host: "gitea.rileymathews.com"
    backend_host: "http://127.0.0.1:3000"

certbot_domains: 
  - "rileymathews.com"

accept_tcp_proxy: false
restic_backup_dirs:
  - /var/lib/gitea/data

dns_records:
  - gitea
