---
available_sites:
  - name: heimdall
    listen_host: start.rileymathews.com
    backend_host: "http://127.0.0.1:8080"

  - name: gatus
    listen_host: gatus.rileymathews.com
    backend_host: "http://127.0.0.1:8081"

accept_tcp_proxy: false
