---
available_sites:
  - name: whoami
    listen_host: "whoami.rileymathews.com"
    backend_host: "http://enterprise:8006"

  - name: whoami-internal
    listen_host: "whoami-ts.rileymathews.com"
    backend_host: "http://enterprise:8006"

accept_tcp_proxy: false
