apiVersion: v1
kind: Service
metadata:
  name: personal-site
  namespace: personal-site
spec:
  ports:
    - name: http
      port: 80
      targetPort: personal-http
  selector:
    app: personal-site
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-personal-site
  namespace: personal-site
spec:
  ingressClassName: nginx
  rules:
    - host: rileymathews.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: personal-site
                port:
                  number: 80
