---
- name: create install directory
  become: yes
  ansible.builtin.file:
    path: /opt/karakeep
    state: directory
    owner: riley
    group: riley

- name: create data dir
  ansible.builtin.file:
    path: /opt/karakeep/data
    state: directory
    owner: riley
    group: riley

- name: copy environment file
  ansible.builtin.template:
    src: env.j2
    dest: /opt/karakeep/.env
    owner: riley
    group: riley

- name: Copy docker compose file
  ansible.builtin.copy:
    src: docker-compose.yml
    dest: /opt/karakeep/docker-compose.yml
    owner: riley
    group: riley

- name: restart_karakeep
  ansible.builtin.shell:
    chdir: /opt/karakeep
    cmd: docker compose pull && docker compose down --remove-orphans && docker compose up -d && docker compose rm
