---
- name: nfs mounts
  include_role:
    name: mount-nfs
  vars:
    nfs_mounts:
      - main/jellyfin

- name: create directories
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: 1000
    group: 1000
    mode: '0755'
  loop:
    - /opt/jellyfin
    - /opt/jellyfin/config
    - /opt/jellyfin/cache

- name: copy docker-compose file
  become: true
  ansible.builtin.copy:
    src: docker-compose.yml
    dest: /opt/jellyfin/docker-compose.yml
    owner: 1000
    group: 1000

- name: restart_jellyfin
  ansible.builtin.shell:
    chdir: /opt/jellyfin
    cmd: docker compose pull && docker compose down --remove-orphans && docker compose up -d && docker compose rm
