services:
  vaultwarden:
    image: vaultwarden/server:1.33.2
    container_name: vaultwarden
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - /mnt/main/vaultwarden/data:/data # the path before the : can be changed
    ports:
      - 8000:80 
