services:
  vaultwarden:
    image: vaultwarden/server:1.34.1
    container_name: vaultwarden
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - /mnt/main/vaultwarden/data:/data # the path before the : can be changed
    ports:
      - 8000:80 
    labels:
      - wud.tag.include=^\d+\.\d+\.\d+$$
