services:
  mealie:
    user: "1000"
    image: ghcr.io/mealie-recipes/mealie:v2.3.0
    container_name: mealie
    restart: unless-stopped
    ports:
      - "9000:9000"
    volumes:
      - ./data:/app/data/
    environment:
      ALLOW_SIGNUP: true
      PUID: 1000
      PGID: 1000
      TZ: America/Chicago
      MAX_WORKERS: 1
      WEB_CONCURRENCY: 1
      BASE_URL: https://mealie.rileymathews.com
      TOKEN_TIME: 720

