---
- name: create install directory
  become: yes
  ansible.builtin.file:
    path: /opt/gatus
    state: directory
    owner: riley
    group: riley

- name: copy environment file
  ansible.builtin.template:
    src: env.j2
    dest: /opt/gatus/.env
    owner: riley
    group: riley

- name: create data directories
  ansible.builtin.file:
    name: "{{ item }}"
    state: directory
    owner: riley
    group: riley
  loop:
    - /opt/gatus/config

- name: copy config file
  ansible.builtin.copy:
    src: config.yml
    dest: /opt/gatus/config/config.yml
    owner: riley
    group: riley
  notify: restart_gatus

- name: Copy docker compose file
  ansible.builtin.copy:
    src: docker-compose.yml
    dest: /opt/gatus/docker-compose.yml
    owner: riley
    group: riley
  notify: restart_gatus

