apiVersion: apps/v1
kind: Deployment
metadata:
  name: rpgweave-staging-celery
  labels:
    app: rpgweave-staging-celery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rpgweave-staging-celery
  template:
    metadata:
      labels:
        app: rpgweave-staging-celery
    spec:
      containers:
        - name: rpgweave-staging-celery
          image: registry.gitlab.com/rpgweave/rpg_weave:latest
          command: ["./bin/celery"]
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: config.settings.staging
            - name: ENCRYPTION_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rpgweave-encryption-password
                  key: ENCRYPTION_PASSWORD
      imagePullSecrets:
        - name: gitlab-registry
