services:
  vikunja:
    image: vikunja/vikunja:0.24.6
    env_file:
      - .env
    ports:
      - 8003:3456
    volumes:
      - ./files:/app/vikunja/files
      - ./db:/db
    restart: unless-stopped
